### ISSUE TITLE
Update @include order guidance

### ISSUE THREAD

**Issue by maya** [18F/frontend#49]
We instruct that users should put `@include`'s before properties, but in the example show `@include`'s at the end of the properties. See Sorting: https://pages.18f.gov/frontend/css-coding-styleguide/format/

``` scss
.module {
  $amount = 3;
  @extend .component;
  @include sizing($amount);
  margin-top: $amount * 1em;
  text-align: center;

  .module__ele {
    color: #fff932;
  }

  @include media($sm) {
    margin-top: ($amount + 10em);
  }
}
```

I realize this is bc it is a media include, however I find this confusing. Can we pick a guidance of all includes before properties or be more explicit about exceptions. I still think that it's confusing to have this as an exception. 

What do others think?
