### ISSUE TITLE
Sass order

### ISSUE THREAD

**Issue by maya** [18F/frontend#65]
I was looking at Thoughtbot's order section of their Sass styleguide https://github.com/thoughtbot/guides/tree/master/style/sass#order:
- Use alphabetical order for declarations.
- Place `@extends` and `@includes` at the top of your declaration list.
- Place media queries directly after the declaration list.
- Place concatenated selectors second.
- Place pseudo-states and pseudo-elements third.
- Place nested elements fourth.
- Place nested classes fifth.

``` scss
.class-one {
  @include mixin;
  background-color: $color-variable;
  border: 0;

  @include media($small-screen) {
    margin: ($spacing-variable * 2) 1rem;
  }

  &::before {
    content: "hello";
  }
}
```

18F's:

Follow ordering:
1. variables
2. `@extend` directives
3. `@include` directives
4. properties

``` scss
.module {
  $amount = 3;
  @extend .component;
  @include sizing($amount);
  margin-top: $amount * 1em;
  text-align: center;

  .module__ele {
    color: #fff932;
  }

  @include media($sm) {
    margin-top: ($amount + 10em);
  }
}
```

Do we have any guidance for ordering of concatenated selectors, pseudo-states and pseudo-elements, nested elements, nested classes?

Based off our example it seems like we place media queries at the end of everything. What's the thought behind that?
